### ISSUE TITLE
docs need ng-include example

### ISSUE THREAD

**Issue by cyrfer** [shanhaichik/webpack-require-loader#2]
I do not understand what I need to do for Webpack to honor `ng-include`.

The current documentation says only:

> Works great with ng-include

I would like to use the following usage:
`<div ng-include="./my-template.html"></div>`

This [SO thread](http://stackoverflow.com/a/34473337/1740008) says we must add the following to our code, which I added to the top of my file that creates the angular app module.
`//@require "./**/*.html"`

When I follow that example, I receive an error when using Webpack-dev-server (tested in angular 1.5.6):

> angular-route.js:1059Error: [$parse:syntax] Syntax Error: Token '.' not a primary expression at column 1 of the expression [./landing.html] starting at [./landing.html].

I anticipate that I need to do something to my webpack.config.js file. I am currently loading HTML via the `raw` loader when defining routes in `app.config`, but it is not clear to me what I should add to my config file, and how the other loaders will be impacted.

**Comment by shanhaichik** [comment]
Hi, @cyrfer !
Thank you for your question.

One of my webpack.config:

``` javascript
// JS
loaders:[
      {
        test: /\.js$/,
        loaders: ['ng-annotate','babel','required?import[]=angular'],
        exclude: /node_modules/
      },
      {
        test: /\.html$/,
        loader: "ng-cache",
        exclude: /node_modules/
      }
     // ...and so on
    ]

// CSS
var cssLoader = {
    test: /\.css$/,
    loader: ExtractTextPlugin.extract("style", "css?sourceMap!postcss!required")
  }
```

You're right, I made a mistake in the example:

``` html
<div ng-include="./my-template.html"></div>
```

It should look like this:

``` html
<div ng-include="'my-template.html'"></div>
```

When using the **// @ require "./**/_.html"_\* with angular, firstly it needs to be installed and configured loader [ng-cache-loader](https://www.npmjs.com/package/ng-cache-loader). Secondly, to apply to the template by its name. No relative paths.
For example:

``` javascript
// Router
.state('app', {
      url: 'hello',
      title: 'Some page',
      views: {
        '': {
          template: 'templatePage.html'
        }
      }
    });

// Component
APP.component('someTable', {
  controller: someTableCtrl,
  templateUrl: 'some-table.html'
});


// ng-include directive
<div ng-include="'my-template.html'"></div>
```

Thirdly, in **ng-include**, file name you need to wrap the single quotes. As an example.
I think I'll write additional description in the near future

**Thank you. Have a nice day!**

**Comment by cyrfer** [comment]
@shanhaichik,

Thank you for the response. I am having trouble to understand how this project helps. I am not clear where this project depends on ng-cache-loader, which I do not want.

My goals are:
- I want to describe the dependencies of my angular JS code and html. When I change the html, I want webpack-dev-server to re-bundle with hot loading. 
- I want to bundle the html with the JS instead of making ajax calls for partials.

Have you tested this project with webpack 2 (beta)?

What does this syntax do? I am still learning parts of webpack.

> required?import[]=angular

Thank you for your advice.

**Comment by shanhaichik** [comment]
@cyrfer !

I will try to explain.
The task of loader is to walk the file tree, folders on the pattern and require them. For example, only JS files or HTML files. 
After that webpack can handle these files. It may compile, copy, collect and do a lot of different magic.

I use **ng-cache** because I don't share the application and its html part. The output I always have one bundle containing both logic and html in the **$templateCache**. ng-cache-loader add templates in the $templateCache, it simplifies access and work.

In your case, if you want to load templates via ajax, you need to use another loader, for example, **file-loader**, as I understand it  should just copy all html files to the static folder. Your ajax calls are going to this folder.

> Have you tested this project with webpack 2 (beta)?

No. I haven't used webpack2, yet. But I can look if needed.

> What does this syntax do? I am still learning parts of webpack
>  required?import[]=angular

This syntax means that in each file will be imported angular.
There is no need to write:

``` javascript
var angular = require("angular");
```

> I want to describe the dependencies of my angular JS code and html. When I change the html, I want webpack-dev-server to re-bundle with hot loading.

It works, I'll use it in several projects. If you have questions, I can make a simple boilerplate with two pages.
The only problem is if you work on windows. But I think that's a problem the webpack-dev-server

**Comment by cyrfer** [comment]
I want to AVOID ajax for html partials. Maybe I do not understand ng-cache-loader. I will try to integrate your suggestions.

I only write `require ('angular')` in one JS file, so it is not a problem for me. I think/hope that means I can avoid that loader to support html also.

I am working on Windows. 

Thank you again!

**Comment by shanhaichik** [comment]
@curfer.

Tomorrow I 'll do a small sample and send it to you .

p.s. I use the loader on projects with dozens of modules and views. And it makes life easier for me . I've done it for this purpose.

**Comment by shanhaichik** [comment]
Hi, @cyrfer . 
How are you doing, got what you wanted? Help is not needed?
I unfortunately did not have time to prepare a demo for you. Dedline :)

**Comment by cyrfer** [comment]
I never understood what this project does for a developer. I recommend you improve the documentation.

I hoped this project would inform Webpack when a developer modifies Angular partials or partials included via `ng-include`. Maybe it does help the developer, but it is not obvious.

Since I cannot find a tool to do what I want, I intend to change my Angular 1.x application to use ES6 template strings so the partial is part of the JS file which Webpack watches.

**Comment by shanhaichik** [comment]
Hi, @cyrfer 
I thought that had already lost you :)
I agree that the documentation does not really talking. I added a couple of days ago, this  [link](https://github.com/shanhaichik/webpack-require-loader/blob/master/ANGULAR.md)

I'm writing a small article on angular+redux+immutable data, I can throw and show how I use it.

The main objective of the loader is to search for files on a mask, and the appearance of a file through **require()**.
Plus it can import variables in the files that it finds. This eliminates the need to write extra code.

If your project is not a secret, and you can see the source code, I can try to see and to help if I can.

**Comment by woohling** [comment]
I really didn't understand how to work with ng-include using this loader either, even after reading the doc multiple times. And even more confusing when I'm using Jade... Still can't figure out how to make it work. Hope the doc could improve.

Currently I'm using HTML-loader and Jade loader (I'm having both html and jade files), and I'm stuck when I met ng-include in the template. I only want to apply your loader for the ng-include templates.  And I'm using angular1.4.

**Comment by shanhaichik** [comment]
Hi, @woohling .
To work angular with html files, use [ng-cache-loader](https://www.npmjs.com/package/ng-cache-loader). 
The main task of the loader is searching files by mask and add a file via require() and import variables. Next they are processed need loaders. For you it **ng-cache-loader**.

**Comment by woohling** [comment]
Thanks~ 😊
I tried using ng-cache-loader, but got stuck 😅. I tried to import html in module, and still won't work.. 
Newbie to webpack, guess I'll have to dig deeper.

**Comment by shanhaichik** [comment]
@woohling 
If you push your code on github, maybe I can watch and help. Today my psychic skills are not very good :)

**Comment by woohling** [comment]
@shanhaichik Thanks in advanced ~~ 
here's one module in simple version: (and I'm using ui-router FYI)
--config folder
   ---- module.route.js
--views folder
   ---- template.html
   ---- partial.html
--controllers folder
   ---- controller.js
--module.js

in template.html 
 `<div><div data-ng-include="'./partial.html'"></div>`

in module.js file:
`require ('ng-cache!./views/partial.html)`;

and in module.route.js 
`$stateProvider.state('module', {
            url: '/module', template: require('../views/template.html')
        })`

I'm using html loader for html files. and I only want to apply ng-cache-loader for ng-include template files. => I'm stuck.
The template isn't included as expected. And the html-minify plugin didn't work either.

**Comment by shanhaichik** [comment]
@woohling 
If you use **ng-cache-loader** you only write file names, no relative paths. They are all added in
[$templateCache](https://docs.angularjs.org/api/ng/service/$templateCache).

``` javascript
<div data-ng-include="'partial.html'">

$stateProvider.state('module', { 
   url: '/module', 
   template: 'template.html'
 })
```

**Comment by woohling** [comment]
@shanhaichik but that's where I'm most confused.  
Currently I'm not applying all my html files using templateCache, only some for `ng-include` usages. I'm intending to put all my html file into one bundle.js file. So I still use `require` to insert my template in route file. 
And if I didn't use relative path and only filenames, how can I know which file to use to insert in the right html file?  (I'm really a newbie to this😅)

**Comment by woohling** [comment]
Hi @shanhaichik  I read the templateCache doc, and found that in order to use it, I need to declare the partial template in `<script id="partial.html'>`. and this script need to be included in the html template. But the fact is I need to use this partial template in multiple html files. So I have to put this partial part in a individual file. Got stuck again😢

**Comment by woohling** [comment]
@shanhaichik  Thanks~  I'll have a try
