### ISSUE TITLE
Question about this loader

### ISSUE THREAD

**Issue by datapimp** [shanhaichik/webpack-require-loader#5]
Hi this looks promising for something I'm trying to do.

Does this only parse comments? Can you show me an example file that you use this on? 

I would love to be able to require an entire tree of files using a pattern, and to extract metadata from the docblock and have it be a part of the module that gets exported.

**Comment by shanhaichik** [comment]
Hi, @datapimp 
Yes, he is now only parses comments and replaces them on the path to the files through require (). For example require ('/path/file.*').

I used it when I was still working with ng1 to import modules and templates to webpack could use.

Examples of use are [here](https://github.com/shanhaichik/webpack-require-loader/blob/master/ANGULAR.md). If not enough, I have to show you.

If you need special cases, we can discuss them. I could make improvements in the separate branches for you.
