### ISSUE TITLE
Dependency on imports-loader

### ISSUE THREAD

**Issue by pavanpaik** [shanhaichik/webpack-require-loader#8]
I really liked this loader and wanted to use in my project. Since i did not have `imports-loader` as a dev dependency in my project i started getting errors when i tried to use this.

I think in your `package.json` if you switch your `dependencies` to `devDependencies` npm will include all of the transitive dependencies automatically.

**Comment by shanhaichik** [comment]
@pavanpaik Done. I hope this will make your work more convenient.

**Comment by pavanpaik** [comment]
@shanhaichik thanks

**Comment by cjhowald** [comment]
I think this was a mistake. The latest version crashes with this error: 

```
Module not found: Error: Can't resolve 'imports-loader'
```

Please revert the dependencies back to `dependencies` from `devDependencies`, since they are required for the loader to run.

**Comment by shanhaichik** [comment]
Hi, @cjhowald 
I'm sorry that it happened.
I revert the dependencies back to dependencies and publish (v1.3.15).

Could you check, I do not have the opportunity to do this now?

**Comment by cjhowald** [comment]
Now it is failing with this error:

```
TypeError: loaderUtils.getOptions is not a function
```

Looks like you need to update your loader-utils dependency to 1.0.0 or above since you are using `getOptions`.

**Comment by shanhaichik** [comment]
@cjhowald , thanks!
I updated the version of loader-utils.

Thank you for your help. 
When I did it for my projects, I did not think that someone would use it)
Have a nice day!

**Comment by cjhowald** [comment]
@shanhaichik confirmed it is fixed. Thanks for the quick response!
